name = "profile-picture-telegram-bot"
main = "src/index.js"
compatibility_date = "2024-02-01"

# Bindings to secrets (to be set in Cloudflare dashboard or via wrangler secret put)
# [vars]
# TELEGRAM_BOT_TOKEN = "example_token"
